baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "OCW Course Hugo Starter"

[module]
  [[module.imports]]
    path = "github.com/mitodl/ocw-course-hugo-theme"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"